pipeline {
    agent any

    environment {
        MODELSIM_HOME = 'C:\\modeltech64_10.6d\\win64'
    }

    stages {
        stage('Checkout') {
            steps {
                // Ensure Jenkins uses the correct Git installation
                script {
                    def gitExecutable = 'C:\\Users\\martin\\AppData\\Local\\Programs\\Git\\bin\\git.exe'
                    def gitUrl = 'https://github.com/MNMenendez/QTMP_VCU.git'
                    bat """
                    "%gitExecutable%" clone "%gitUrl%"
                    """
                }
            }
        }

        stage('Setup') {
            steps {
                echo "ModelSim Home: ${env.MODELSIM_HOME}"
            }
        }

        stage('Compile') {
            steps {
                script {
                    bat """
                    "%MODELSIM_HOME%\\vsim.exe" -c -do "vlib work; vcom -2008 and_gate.vhdl and_gate_tb.vhdl"
                    """
                }
            }
        }

        stage('Run Simulation') {
            steps {
                script {
                    bat """
                    "%MODELSIM_HOME%\\vsim.exe" -c -do "run -all; quit"
                    """
                }
            }
        }

        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: '**/test_results.log', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Tests passed successfully!'
        }
        failure {
            echo 'Tests failed. Please check the logs.'
        }
    }
}
